### ISSUE TITLE
Autoadjust "Spacer between genomes in the linear Layout"

### ISSUE THREAD

**Issue by iimog** [BioInf-Wuerzburg/AliTV#31]
The spacer between genomes in the linear layout can be automatically calculated to use the vertical space. So the user can change the canvas height in order to change the spacing between genomes.
Otherwise those parameters have to be adjusted simultanously.
![genomespacerproblem](https://cloud.githubusercontent.com/assets/7403236/7677814/aafe73e6-fd4f-11e4-9f3e-5f909a99d91d.png)
The function should be similar to getOuterRadius for the circular layout. Remove the conf value and replace it with a getter function that dynamically calculates the value. Add tests to check if the value is calculated correctly for different number of genomes and different heights.

**Comment by sonjahohlfeld** [comment]
Add this enhancement and make the drawing more dynamically.
