### ISSUE TITLE
Autoadjust "Spacer between genomes in the linear Layout" wastes space

### ISSUE THREAD

**Issue by iimog** [BioInf-Wuerzburg/AliTV#35]
The calculation of the genome distance wastes vertical space due to the way it is calculated:
```{javascript}
var genomeDistance = this.getCanvasHeight() * 1 / this.filters.karyo.genome_order.length;
```
Because there is one less spacer required than there are genomes, the denominator can be decreased by one. However there is one additional karyoHeight required otherwise the last genome is just outside of the canvas (substract this from the numerator):
```{javascript}
var genomeDistance = (this.getCanvasHeight() - this.getKaryoHeight) / (this.filters.karyo.genome_order.length - 1);
```
Tests have to be updated.

**Comment by sonjahohlfeld** [comment]
Add the better calculation of the genomeSpacer and updated the tests for it.
