### ISSUE TITLE
Hiding of elements with non-unique names

### ISSUE THREAD

**Issue by iimog** [BioInf-Wuerzburg/AliTV#52]
When trying to hide an element with a non unique-name with the context menu only the first one in features array is hidden. That is not necessarily the one which was clicked on. Furthermore it is not possible to hide the other one.
Reproduce with demo:
 - Right click on the ```ycf2``` feature in the second inverted repeat of *O. europaea*.
 - Select ```Hide```. 
 - The ```ycf2``` in the first inverted repeat disappears while this one remains.
 - Repeat the procedure multiple times. 
 - Nothing else happens.

**Comment by sonjahohlfeld** [comment]
The problem occurs when you select a feature which appears more than once on the same genome. For example ycf2 appears twice on *O. europaea*. 
For fixing the bug it may help to add exact Ids to all features in the perl-script (in the same way links have an id). Then the exact hiding of features should be possible.
